### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by corysimmons** [willfarrell/alfred-caniuse-workflow#11]
How often does this get updated or does it pull from caniuse directly? AlleyOop link starts off with "this is super insecure".

**Comment by willfarrell** [comment]
It caches their entire DB for 7 days. You can change it in the source on your end if you need shorter.
Looks like I don't even have AlleyOop installed any more. I'll add an issue to remove it from the workflow.

**Comment by corysimmons** [comment]
Thanks. Maybe add a note to the README that explains that the CanIUse DB is updated every 7 days automatically as well.
