### ISSUE TITLE
doesn't work on Alfred v2.8.6 (411)

### ISSUE THREAD

**Issue by vyorkin** [willfarrell/alfred-caniuse-workflow#15]
Alfred says that I need to update to the pre-release version:
![image](https://cloud.githubusercontent.com/assets/988849/20245519/4924a948-a9b4-11e6-82e6-f4fd3c05b5a3.png)

**Comment by willfarrell** [comment]
Try an older release like v1.7, or maybe v1.6. Note that all future release will be for the latest version of Alfred.

https://github.com/willfarrell/alfred-caniuse-workflow/releases

**Comment by vyorkin** [comment]
ok, thanks!
