### ISSUE TITLE
Incompatible with Alfred 2?

### ISSUE THREAD

**Issue by IanVS** [willfarrell/alfred-caniuse-workflow#17]
I just downloaded version 1.8, and when I try to enable it I see:

![image](https://cloud.githubusercontent.com/assets/4616705/21988708/37ab9754-dbd6-11e6-9221-323a040ef6e3.png)

But the README specifies Alfred version 2.  Can you please confirm the compatibility of this workflow with Alfred 2?

**Comment by willfarrell** [comment]
It seems alfred only exports for the latest version installed I'm afraid, and no way to export a v2 from v3. There is nothing v3 specific in the code. I've updated the README to better reflect this.

**Solution:** Upgrade Alfred **OR** download an older version of this workflow and apply the code changes if needed.

Sorry I couldn't be more help.

**Comment by IanVS** [comment]
Thanks, can you say what the last version which supports Alfred 2 is?  That might be nice to add to the README as well.  (Also, the readme still mentions Alfred 2 further down).

**Comment by willfarrell** [comment]
likely v1.7
